spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/java_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update

orm-type: jpa

application:
  worker-mail: ustiinovmp@gmail.com
  mail:
    enabled: false